//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korpusy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arkusz1
    {
        public int Identyfikator { get; set; }
        public string Pole2 { get; set; }
    }
}
