//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korpusy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDFTrainingEntities : DbContext
    {
        public PDFTrainingEntities()
            : base("name=PDFTrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t1> t1 { get; set; }
        public virtual DbSet<theMostPopularWordsGoogle> theMostPopularWordsGoogle { get; set; }
        public virtual DbSet<Arkusz1> Arkusz1 { get; set; }
        public virtual DbSet<SOFRep> SOFRep { get; set; }
        public virtual DbSet<SpecialOperations> SpecialOperations { get; set; }
        public virtual DbSet<słownik> słownik { get; set; }
    }
}
