//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korpusy
{
    using System;
    using System.Collections.Generic;
    
    public partial class słownik
    {
        public int ID { get; set; }
        public string EN { get; set; }
        public string PL { get; set; }
        public string EN_opis { get; set; }
        public string PL_opis { get; set; }
        public Nullable<int> ugr_tematyczne { get; set; }
        public string ilustracje { get; set; }
        public string komentarz { get; set; }
        public string EN_acr { get; set; }
        public string PL_acr { get; set; }
        public Nullable<int> część_mowy { get; set; }
        public string skojarzenie { get; set; }
        public Nullable<System.DateTime> data_wprowadzenia { get; set; }
        public Nullable<bool> oficjalne { get; set; }
    }
}
